version: '3.2'
services:
    worker:
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - type: bind
              source: .
              target: /app
        links:
            - rabbit
        depends_on:
            - rabbit
    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=myuser
            - RABBITMQ_DEFAULT_PASS=mypassword
            - RABBITMQ_DEFAULT_VHOST=vhost
        ports:
            - "5672:5672"
            
    flower:  
        hostname: flower
        image:  mher/flower:latest
        environment:
            - CELERY_BROKER_URL=amqp://myuser:mypassword@rabbit:5672/
            - FLOWER_PORT=8889
        ports:  
            - 8889:8889

